### ISSUE TITLE
Current user profile is not logged in for https://myactivity.google.com

### ISSUE THREAD

**Issue by ghost** [jpathy/google-myactivity#1]
gmusic_activity is producing the above error even though the browser is logged into https://myactivity.google.com

Steps to reproduce:

1. open chrome
2. go to https://myactivity.google.com
3. sign in
4. exit chrome (you can reopen chrome and load myactivity.google.com to confirm you're still logged in)
5. launch gmusic_activity get
6. observe the above error

expected behaviour:

the app obtains the information from https://myactivity.google.com and displays it.

**Comment by jpathy** [comment]
I pushed a commit to address this. Can you try again from latest master?

**Comment by ghost** [comment]
working now. thanks
